# Generated by Django 5.2 on 2025-04-29 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_casa', models.CharField(max_length=100)),
                ('time_fora', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.CharField(max_length=100)),
                ('tipo_acao', models.CharField(max_length=100)),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('tempo', models.IntegerField(choices=[(1, '1º Tempo'), (2, '2º Tempo')])),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoutApp.partida')),
            ],
        ),
    ]
